# -*- coding: utf-8 -*-
"""AvaliaçãoParcial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGR8vFFRhBY0QF2R3RD4cIYMFfRgqQuS
"""

tempo = int(input("Digite tempo de viagem: "))
distancia = int(input("Digite distância percorrida: "))
litros = float((tempo * distancia)/12)

print(f"Quantidade de litros: ", f"{i:.3f}")

tempo = int(input("Digite tempo de viagem: "))
distancia = int(input("Digite distância percorrida: "))
litros = float((tempo * distancia)/12)

i = litros
while i == litros:
  print(f"Quantidade de litros: ", f"{i:.3f}")
  break