# -*- coding: utf-8 -*-
"""def_Phyton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFeD66Bdl-TQ60DUY56aIxSoSeRiZmdV
"""

def mediana_idades(idade1, idade2, idade3):
    idades = [idade1, idade2, idade3]
    idades.sort()
    return idades[1]
idade1 = int(input("Digite a primeira idade: "))
idade2 = int(input("Digite a segunda idade: "))
idade3 = int(input("Digite a terceira idade: "))
mediana = mediana_idades(idade1, idade2, idade3)
print(f"A idade de Camila é: {mediana}")

def idade_voto_eleição_presidencial(idade):
    if idade >= 16:
        return "Você pode votar."
    else:
        return "Você não pode votar."

idade_eleitor = int(input("Digite a sua idade: "))
apto_para_votar = idade_voto_eleição_presidencial(idade_eleitor)
print(apto_para_votar)

def dividir(numero,divisor):
    if divisor == 0:
        return "Erro: Divisão por zero não é permitida."
    else:
        return numero / divisor

sobra_divisão = dividir(10, 6)
print(sobra_divisão)



def dividir(numero,divisor):
    if divisor == 0:
        return "Erro: Divisão por zero não é permitida."
    else:
        return numero / divisor

sobra_divisão = dividir(int(input("Digite o Número a ser  divido:")), int(input("Digite o Número divisor:")))
print(sobra_divisão)

def dividir(numero, divisor):
    if divisor == 0:
        return "Erro: Por favor, insira valores numéricos válidos."
    return numero / divisor

try:
    numero = float(input("Digite o número a ser dividido: "))
    divisor = float(input("Digite o divisor: "))

    resultado = dividir(numero, divisor)
    print("Resultado da divisão:", resultado)
except ValueError:
    print("Erro: Por favor, insira valores numéricos válidos.")

def dividir(numero, divisor):
    if divisor == 0:
        return "Erro: Divisão por zero não é permitida."
    return numero / divisor

try:
    numero = float(input("Digite o número a ser dividido: "))
    divisor = float(input("Digite o divisor: "))

    resultado = dividir(numero, divisor)
    print("Resultado da divisão:", resultado)
except ValueError:
    print("Erro: Por favor, insira valores numéricos válidos.")

def dividir(numero, divisor):
    try:
        if divisor == 0:
            raise ValueError(" Por favor, insira valores numéricos válidos.")
        return numero / divisor
    except ValueError as sobra_divisão:
        return str(sobra_divisão)

sobra_divisão = dividir(10, 5)
print("A sobra da Divisão dessa é:" , sobra_divisão)

def soma(a, b):
    return a + b

def subtracao(a, b):
    return a - b

def multiplicacao(a, b):
    return a * b

def divisao(a, b):
    if b == 0:
        raise ValueError("Erro: Divisão por zero não é Calculável.")
    return a / b

def calculadora():
    print("Calculadora Simples")
    print("Selecione a operação:")
    print("1: Adição")
    print("2: Subtração")
    print("3: Multiplicação")
    print("4: Divisão")

    while True:
        try:
            operacao = input("Escolha uma operação (1/2/3/4): ")

            if operacao not in ['1', '2', '3', '4']:
                raise ValueError("Operação inválida. Por favor, escolha 1, 2, 3 ou 4.")

            num1 = float(input("Digite o primeiro número: "))
            num2 = float(input("Digite o segundo número: "))

            if operacao == '1':
                resultado = soma(num1, num2)
                print(f"{num1} + {num2} = {resultado}")
            elif operacao == '2':
                resultado = subtracao(num1, num2)
                print(f"{num1} - {num2} = {resultado}")
            elif operacao == '3':
                resultado = multiplicacao(num1, num2)
                print(f"{num1} * {num2} = {resultado}")
            elif operacao == '4':
                resultado = divisao(num1, num2)
                print(f"{num1} / {num2} = {resultado}")

            break # Encerrar o loop após uma operação bem-sucedida
        except ValueError as e:
            print(e)
            print("Tente novamente")

if __name__ == "__main__":

  calculadora()
print("Obrigado por utilizar a nossa calculadora! 😉" )

def soma(a, b):
    return a + b

def subtracao(a, b):
    return a - b

def multiplicacao(a, b):
    return a * b

def divisao(a, b):
    if b == 0:
        raise ValueError("Erro: Divisão por zero não é calculável.")
    return a / b

def calculadora():
    print("Calculadora Simples")
    print("Selecione a operação:")
    print("1: Adição")
    print("2: Subtração")
    print("3: Multiplicação")
    print("4: Divisão")

    while True:
        try:
            operacao = input("Escolha uma operação (1/2/3/4): ")

            if operacao not in ['1', '2', '3', '4']:
                raise ValueError("Operação inválida. Por favor, escolha 1, 2, 3 ou 4.")

            num1 = float(input("Digite o primeiro número: "))
            num2 = float(input("Digite o segundo número: "))

            if operacao == '1':
                resultado = soma(num1, num2)
                print(f"O resultado da sua adição é: {num1} + {num2} = {resultado}")
            elif operacao == '2':
                resultado = subtracao(num1, num2)
                print(f"O resultado da sua subtração é: {num1} - {num2} = {resultado}")
            elif operacao == '3':
                resultado = multiplicacao(num1, num2)
                print(f"O resultado da sua multiplição é: {num1} * {num2} = {resultado}")
            elif operacao == '4':
                resultado = divisao(num1, num2)
                print(f"O resultado da sua divisão é: {num1} / {num2} = {resultado}")

            break  # Encerrar o loop após uma operação bem-sucedida
        except ValueError as e:
            print(e)
            print("Tente novamente")

if __name__ == "__main__":
    calculadora()
    print("Obrigado por utilizar a nossa calculadora! 😉")

def mes_por_extenso(mes):
    meses = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
    ]
    return meses[mes - 1] if 1 <= mes <= 12 else None

def validar_data(dia, mes, ano):
    if mes < 1 or mes > 12:
        return False
    if dia < 1 or dia > 31:
        return False
    if mes in [4, 6, 9, 11] and dia == 31:
        return False
    if mes == 2:
        if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
            return dia <= 29  # Ano bissexto
        return dia <= 28
    return True

def data_formatada(data):
    try:
        dia, mes, ano = map(int, data.split('/'))

        if not validar_data(dia, mes, ano):
            return None

        mes_extenso = mes_por_extenso(mes)
        if mes_extenso:
            return f"{dia} de {mes_extenso} de {ano}"
        else:
            return None

    except ValueError:
        return None


data_input = "25/12/2023"
resultado = data_formatada(data_input)
if resultado:
    print(resultado)
else:
    print("Data inválida")

def mes_por_extenso(mes):
    meses = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
    ]
    return meses[mes - 1] if 1 <= mes <= 12 else None

def validar_data(dia, mes, ano):
    if mes < 1 or mes > 12:
        return False
    if dia < 1 or dia > 31:
        return False
    if mes in [4, 6, 9, 11] and dia == 31:
        return False
    if mes == 2:
        if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
            return dia <= 29  # Ano bissexto
        return dia <= 28
    return True

def data_formatada(data):
    try:
        dia, mes, ano = map(int, data.split('/'))

        if not validar_data(dia, mes, ano):
            return None

        mes_extenso = mes_por_extenso(mes)
        if mes_extenso:
            return f"{dia} de {mes_extenso} de {ano}"
        else:
            return None

    except ValueError:
        return None

# Exemplo de uso
data_input = "25/12/2023"
resultado = data_formatada(data_input)
if resultado:
    print(resultado)  # Saída: "25 de dezembro de 2023"
else:
    print("Data inválida")

def mes_por_extenso(mes):
    meses = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
    ]
    return meses[mes - 1] if 1 <= mes <= 12 else None

def validar_data(dia, mes, ano):
    if mes < 1 or mes > 12:
        return False
    if dia < 1 or dia > 31:
        return False
    if mes in [4, 6, 9, 11] and dia == 31:
        return False
    if mes == 2 and dia > 28:
        return False  # Fevereiro sempre terá 28 dias

    return True

def data_formatada(data):
    try:
        dia, mes, ano = map(int, data.split('/'))

        if not validar_data(dia, mes, ano):
            return None

        mes_extenso = mes_por_extenso(mes)
        if mes_extenso:
            return f"{dia} de {mes_extenso} de {ano}"
        else:
            return None

    except ValueError:
        return None

# Exemplo de uso
data_input = "25/12/2023"
resultado = data_formatada(data_input)
if resultado:
    print(resultado)  # Saída: "25 de dezembro de 2023"
else:
    print("Data inválida")

def mes_por_extenso(mes):
    meses = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]
    return meses[mes - 1] if 1 <= mes <= 12 else None # Fixed indentation
def validar_data(dia, mes, ano):
    if mes < 1 or mes > 12:
        return False
    if dia < 1 or dia > 31:
        return False
    if mes in [4, 6, 9, 11] and dia == 31:
        return False
    if mes == 2:
        if (ano % 4 == 0 and ano % 100 !=0) or (ano % 400 == 0):
            return dia <= 29 # Ano bissexto
        return dia <= 28
    return True
def data_formatada(data):
    try:
        dia, mes, ano = map(int, data.split('/'))

        if not validar_data(dia, mes, ano):
            return None
        mes_extenso = mes_por_extenso(mes)
        if mes_extenso:
            return f"{dia} de {mes_extenso} de {ano}"
        else:
            return None
    except ValueError:
        return None
data_input = "25/12/2023"
resultado = data_formatada(data_input)
if resultado:
    print(resultado)
else:
    print("Data inválida")

def mes_por_extenso(mes):
    meses = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
    ]
    return meses[mes - 1] if 1 <= mes <= 12 else None

def validar_data(dia, mes, ano):
    if mes < 1 or mes > 12:
        return False
    if dia < 1 or dia > 31:
        return False
    if mes in [4, 6, 9, 11] and dia == 31:
        return False
    if mes == 2 and dia > 28:
        return False

    return True

def data_formatada(data):
    try:
        dia, mes, ano = map(int, data.split('/'))

        if not validar_data(dia, mes, ano):
            return None

        mes_extenso = mes_por_extenso(mes)
        if mes_extenso:
            return f"{dia} de {mes_extenso} de {ano}"
        else:
            return None

    except ValueError:
        return None


data_input = input("Digite a data no formato DD/MM/AAAA: ")
resultado = data_formatada(data_input)
if resultado:
    print(resultado)
else:
    print("Data inválida")

def mes_por_extenso(mes):
    meses = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
    ]
    return meses[mes - 1] if 1 <= mes <= 12 else None

def validar_data(dia, mes, ano):
    if mes < 1 or mes > 12:
        return False
    if dia < 1 or dia > 31:
        return False
    if mes in [4, 6, 9, 11] and dia == 31:
        return False
    if mes == 2:
        # Verifica se o ano é bissexto
        if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
            return dia <= 29
        return dia <= 28

    return True

def data_formatada(data):
    try:
        dia, mes, ano = map(int, data.split('/'))

        if not validar_data(dia, mes, ano):
            return None

        mes_extenso = mes_por_extenso(mes)
        if mes_extenso:
            return f"{dia} de {mes_extenso} de {ano}"
        else:
            return None

    except ValueError:
        return None

# Solicitar a entrada do usuário
data_input = input("Digite a data no formato DD/MM/AAAA: ")
resultado = data_formatada(data_input)
if resultado:
    print(resultado)  # Exibe a data formatada
else:
    print("Data inválida")

import random

def embaralhar_palavra(palavra, caixa='alta'):
    # Converte a palavra para caixa alta ou caixa baixa
    if caixa == 'alta':
        palavra = palavra.upper()
    else:
        palavra = palavra.lower()

    # Converte a string em uma lista de caracteres
    lista_caracteres = list(palavra)

    # Embaralha a lista de caracteres
    random.shuffle(lista_caracteres)

    # Converte a lista de volta para uma string
    return ''.join(lista_caracteres)

# Exemplo de uso
palavra_input = input("Digite uma palavra: ")
resultado = embaralhar_palavra(palavra_input, caixa='alta')  # Pode usar 'baixa' também
print(resultado)

def embaralhar_palavra(palavra, caixa='baixa'):
    # Converte a palavra para caixa alta ou caixa baixa
    if caixa == 'alta':
        palavra = palavra.upper()
    else:
        palavra = palavra.lower()

    # Converte a string em uma lista de caracteres
    lista_caracteres = list(palavra)

    # Embaralha a lista de caracteres
    random.shuffle(lista_caracteres)

    # Converte a lista de volta para uma string
    return ''.join(lista_caracteres)

# Exemplo de uso
palavra_input = input("Digite uma palavra: ")
resultado = embaralhar_palavra(palavra_input, caixa='baixa')  # Pode usar 'baixa' também
print(resultado)

def embaralhar_palavra(palavra, caixa='baixa'):
    # Converte a palavra para caixa alta ou caixa baixa
    if caixa == 'alta':
        palavra = palavra.upper()
    else:
        palavra = palavra.lower()

    # Converte a string em uma lista de caracteres
    lista_caracteres = list(palavra)

    # Embaralha a lista de caracteres
    random.shuffle(lista_caracteres)

    # Constrói a string manualmente
    resultado = ""
    for caracter in lista_caracteres:
        resultado += caracter

    return resultado

# Exemplo de uso
palavra_input = input("Digite uma palavra: ")
resultado = embaralhar_palavra(palavra_input, caixa='baixa')  # Pode usar 'baixa' também
print(resultado)