# -*- coding: utf-8 -*-
"""Phyton050924

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBRHsh06TnkEchZINmXbKF-J3oOW7pVf
"""

contador = 0
nome = input("Digite seu nome:")
while contador < 10:
  print("Olá", nome)
  contador += 1

lista = []

contador = 1
while contador <= 3:
  contador += 1
  media = float(input("Digite Média:"))
  lista.append(media)
soma = sum(lista) / contador
print("A média é:", soma)

contador = 0
soma = 0
while contador < 101:
  if contador % 2 == 0:
     contador += 2
     soma += contador
  if contador == 100:
    break
print("A soma dos números pares até 100 é:", soma)

contador= 0
numero= int(input("Digite seu Número:"))
while contador  <= 9:
  contador += 1
  resultado = numero * contador
  print(numero, "x", contador, "=", resultado)



contador = 0
soma = 0
while contador < 15:
     contador += 1
     soma += contador
print("A soma dos números de 1 até 15 é:", soma)