# -*- coding: utf-8 -*-
"""Phyton050924

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBRHsh06TnkEchZINmXbKF-J3oOW7pVf
"""

contador = 0
nome = input("Digite seu nome:")
while contador < 10:
  print("Olá", nome)
  contador += 1

lista = []

contador = 1
while contador <= 3:
  contador += 1
  media = float(input("Digite Média:"))
  lista.append(media)
soma = sum(lista) / contador
print("A média é:", soma)

contador = 0
soma = 0
while contador < 101:
  if contador % 2 == 0:
     contador += 2
     soma += contador
  if contador == 100:
    break
print("A soma dos números pares até 100 é:", soma)

contador= 0
numero= int(input("Digite seu Número:"))
while contador  <= 9:
  contador += 1
  resultado = numero * contador
  print(numero, "x", contador, "=", resultado)

contador = 0
soma = 0
while contador < 15:
     contador += 1
     soma += contador
print("A soma dos números de 1 até 15 é:", soma)

lista = []
contador = 1
while contador <= 3:
  contador += 1
  idade= input("Digite sua idade:")
  lista.append(idade)
print("As idades das irmãs são:", lista)
if lista[0] < lista[1] and lista[1] < lista[2]:
  print("A idade de camila é:", lista[0])
elif lista[1] < lista[0] and lista[1] < lista[2]:
  print("A idade de camila é:", lista[1])
else:
  print("A idade de camila é:", lista[2])

"""EXERCÍCIO ACIMA

Cibele, Camila e Celeste são três irmãs inseparáveis. Estão sempre juntas e adoram fazer esportes, ler, cozinhar, jogar no computador... Agora estão aprendendo a programar computadores para desenvolverem seus próprios jogos.


---


Mas nada disso interessa para esta tarefa: estamos interessados apenas nas suas idades. Sabemos que Cibele nasceu antes de Camila e Celeste nasceu depois de Camila.

Dados três números inteiros indicando as idades das irmãs, escreva um programa para determinar a idade de Camila.

Entrada
A entrada é composta por três linhas, cada linha contendo um número inteiro N, a idade de uma das irmãs.

Saída
Seu programa deve produzir uma única linha, contendo um único número inteiro, a idade de Camila.
"""